services:

  mysql:

version: "3.8"

services:
  db:

    image: mysql:8.0
    container_name: emp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees_db
      MYSQL_USER: aya
      MYSQL_PASSWORD: aya
    ports:
      - "3306:3306"
    volumes:

      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - emp-network

  app:
    image: ayasouki/emp-app:1.0
    container_name: emp_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8090:8080"
    networks:
      - emp-network

volumes:
  mysql_data:

networks:
  emp-network:
    driver: bridge

      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: emp_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8080"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: employees_db
      DB_USER: aya
      DB_PASSWORD: aya

volumes:
  dbdata:

